services:
  database:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "mlops2425"
      MYSQL_USER: "mysql2"
      MYSQL_PASSWORD: "a"
      MYSQL_DATABASE: "webapp"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysql', '--user=root', '--password=mlops2425', '--execute', 'SHOW DATABASES;']
      interval: 3s
      retries: 5

  webapp:
    image: vborghys/webapp
    ports:
      - "3000:3000"
    environment:
      MYSQL_URL: "mysql://root:mlops2425@database/webapp"
      
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'localhost:3000']
      interval: 2s
      retries: 5

  tests:
    image: vborghys/webapp
    entrypoint: 'yarn test'
    depends_on:
      webapp:
        condition: service_healthy
    environment:
      API_URL: http://webapp:3000
    volumes:
      - ./tests:/app/tests

volumes:
  db-data:
    name: webapp-database
