---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: 'yarn install'

      - name: run linter
        run: 'yarn lint'
