---
name: Build and test
on:
  push:
    branches:
      - main
env:
  ESLINT_USE_FLAT_CONFIG: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: 'yarn install'

      - name: run linter
        run: 'yarn lint'

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: build Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: vborghys/webapp:latest
